# Import LaunchDescription which represents the entire launch configuration.
# Every ROS2 launch file must return a LaunchDescription object containing
# all the nodes and actions that should be started.
from launch import LaunchDescription

# Import Node action which allows launching ROS2 nodes from a launch file.
from launch_ros.actions import Node

# Utility function used to locate the installed path of a ROS2 package.
# It returns the directory path of the package from the workspace install space.
from ament_index_python.packages import get_package_share_directory

# Python library used for constructing file paths in a platform-independent way.
import os


# Main function required by the ROS2 launch system.
# This function returns the LaunchDescription object containing all nodes to launch.
def generate_launch_description():

    # ---------------------------------------------------------
    # Locate the navigation package directory
    # ---------------------------------------------------------

    # Get the directory path of the 'testbed_navigation' package.
    # This package contains the navigation configuration files.
    pkg_dir = get_package_share_directory('testbed_navigation')

    # Construct the full path to the Nav2 parameter file.
    # This YAML file contains parameters for:
    # - planner server
    # - controller server
    # - behavior tree navigator
    # - behavior server
    nav2_params = os.path.join(pkg_dir, 'config', 'nav2_params.yaml')


    # ---------------------------------------------------------
    # Planner Server Node
    # ---------------------------------------------------------

    # The planner server computes the global path from the robot's current pose
    # to the goal pose. It uses the global costmap and a planning algorithm
    # such as NavFn (Dijkstra/A* based planner).
    planner_server = Node(
        package='nav2_planner',          # Package containing the global planner server
        executable='planner_server',     # Planner server executable
        name='planner_server',           # Node name visible in ROS graph
        output='screen',                 # Print logs directly to terminal
        parameters=[nav2_params],        # Load planner parameters from YAML file
    )


    # ---------------------------------------------------------
    # Controller Server Node
    # ---------------------------------------------------------

    # The controller server follows the global path generated by the planner.
    # It generates velocity commands (cmd_vel) for the robot.
    # In your configuration it uses the Regulated Pure Pursuit controller.
    controller_server = Node(
        package='nav2_controller',        # Package containing local controller server
        executable='controller_server',   # Controller server executable
        name='controller_server',         # Node name
        output='screen',                  # Print logs to terminal
        parameters=[nav2_params],         # Load controller parameters
    )


    # ---------------------------------------------------------
    # Behavior Tree Navigator Node
    # ---------------------------------------------------------

    # The bt_navigator orchestrates the entire navigation process
    # using a Behavior Tree (BT).
    #
    # It coordinates:
    # - path planning
    # - path following
    # - recovery behaviors
    #
    # The navigation logic is defined in an XML behavior tree file.
    bt_navigator = Node(
        package='nav2_bt_navigator',      # Package implementing BT-based navigation
        executable='bt_navigator',        # Behavior tree navigator executable
        name='bt_navigator',              # Node name
        output='screen',                  # Print logs to terminal
        parameters=[nav2_params],         # Load behavior tree configuration
    )


    # ---------------------------------------------------------
    # Behavior Server Node
    # ---------------------------------------------------------

    # The behavior server implements recovery behaviors that help
    # the robot recover from navigation failures.
    #
    # Examples include:
    # - clearing costmaps
    # - rotating in place
    # - backing up
    # - waiting
    behavior_server = Node(
        package='nav2_behaviors',         # Package implementing recovery behaviors
        executable='behavior_server',     # Behavior server executable
        name='behavior_server',           # Node name
        output='screen',                  # Print logs to terminal
        parameters=[nav2_params],         # Load parameters
    )


    # ---------------------------------------------------------
    # Lifecycle Manager Node
    # ---------------------------------------------------------

    # Nav2 nodes use the ROS2 lifecycle model.
    # Nodes start in an "unconfigured" state and must transition through:
    #
    # unconfigured → inactive → active
    #
    # The lifecycle manager automatically transitions nodes through
    # these states so they become operational.
    lifecycle_manager = Node(
        package='nav2_lifecycle_manager',        # Package responsible for lifecycle control
        executable='lifecycle_manager',          # Lifecycle manager executable
        name='lifecycle_manager_navigation',     # Name of lifecycle manager node
        output='screen',                         # Print logs to terminal
        parameters=[
            {'use_sim_time': True},              # Use simulation time (required for Gazebo)
            {'autostart': True},                 # Automatically configure and activate nodes
            {'node_names': [                     # List of lifecycle nodes to manage
                'planner_server',
                'controller_server',
                'bt_navigator',
                'behavior_server'
            ]}
        ]
    )


    # ---------------------------------------------------------
    # Launch Description
    # ---------------------------------------------------------

    # Return LaunchDescription containing all navigation nodes.
    #
    # This launch file starts the full Nav2 navigation stack:
    #
    # 1. planner_server  → computes global path
    # 2. controller_server → follows path and generates velocity commands
    # 3. bt_navigator → coordinates navigation behavior
    # 4. behavior_server → handles recovery behaviors
    # 5. lifecycle_manager → activates all navigation nodes automatically
    return LaunchDescription([
        planner_server,
        controller_server,
        bt_navigator,
        behavior_server,
        lifecycle_manager
    ])